### ISSUE TITLE
stop changing chromosome names

### ISSUE THREAD

**Issue by tjparnell** [HuntsmanCancerInstitute/USeq#5]
SamTranscriptomeParser silently changes chromosome MT to M, but inconsistently, resulting in both MT and M sequences in the header dictionary. Providing a sam header with -h doesn't help unless you include both sequence names. This breaks downstream applications with Picard and GATK that require matching reference and bam sequence dictionaries.

In edu.utah.seq.data.sam, fixChromosomeName

**Comment by DavidAustinNix** [comment]
OK fixed and released under USeq_9.1.3. Thanks for the catch.  -cheers, D
