### ISSUE TITLE
"Consensus" function cannot extract barcode.

### ISSUE THREAD

**Issue by esamorodnitsky** [HuntsmanCancerInstitute/USeq#7]
I tried running the "Cluster" function, but got this. What is wrong here?

Clustering and calling consensus on 24 chunks (Thread Region RamUsed Time):
ERROR: could not extract a BMF barcode from the following alignment:
cfDNA_run2:1:1108:5904:22137 163     chr1    166054  0       82M19S  =       166054  82      CAGGCTGGGCACAGTGGCTCACACCTGTAATCCCAGCAGTTTGGGAGGCCGAGGCAGGCAGATCATGAGGTCAGGAGTTCGAAGATCGGAAGAGCGTCGTG        AAA?AFFBAABAGB45FFFGGGHH?FHHH6GHHHHHHC2ADGHFDFG?FGGGGGGGG?EHFGFHGHHHHH?EGF2@FBFFFHAFEDGGGEFEHHHGAGF/E   MC:Z:19S82M  MD:Z:82 PG:Z:bwa        RG:Z:cf.1    NM:i:0  MQ:i:0  UQ:i:0  AS:i:82 XT:i:83 QX:Z:CCCBGGGGG  RX:Z:GCGCGGCGG

**Comment by DavidAustinNix** [comment]
Addressed in email exchange.  One needs to run several additional applications before Consensus is called as detailed in these Snakemake workflows: https://github.com/HuntsmanCancerInstitute/Workflows/tree/master/Hg38RunnerWorkflows/DnaConsensusAlignQC
